const withPlugins = require('next-compose-plugins');
const { VanillaExtractPlugin } = require('@vanilla-extract/webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = withPlugins(
  [new VanillaExtractPlugin(), new MiniCssExtractPlugin()],
  {
    reactStrictMode: true,
    webpack: (config, options) => {
      config.module.rules.push({
        test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: require.resolve('css-loader'),
            options: {
              url: false // Required as image imports should be handled via JS/TS import statements
            }
          }
        ]
      });
      return config;
    }
  }
);
